# Generated by Django 5.1.5 on 2025-03-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactioncustomer',
            name='transaction_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
