# Generated by Django 5.1.5 on 2025-03-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallettransactionsadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransactionsadmin',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=100),
        ),
    ]
