# Generated by Django 5.1.5 on 2025-03-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallettransactionsadmin_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransactionsadmin',
            name='transaction_through',
            field=models.CharField(choices=[('bank', 'Bank'), ('wallet', 'Wallet'), ('cash', 'Cash')], max_length=100),
        ),
    ]
