# Generated by Django 5.1.5 on 2025-03-21 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0014_orderitems_payment_done_to_vendor'),
        ('wallet', '0006_commissionrecievedadminperorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionrecievedadminperorder',
            name='order_item',
        ),
        migrations.AddField(
            model_name='commissionrecievedadminperorder',
            name='order',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='cart_and_orders.order'),
            preserve_default=False,
        ),
    ]
