# Generated by Django 5.1.5 on 2025-04-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0014_orderitems_payment_done_to_vendor'),
        ('wallet', '0007_remove_commissionrecievedadminperorder_order_item_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallettransactionsvendor',
            unique_together={('order_item', 'transaction_type')},
        ),
    ]
