# Generated by Django 5.1.5 on 2025-02-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_time', models.DateTimeField()),
                ('coupon_type', models.CharField(max_length=100)),
                ('max_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
