# Generated by Django 5.1.5 on 2025-03-08 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='expiry_time',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('flat', 'Flat'), ('percentage', 'Percentage')], default='flat', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=100.00, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2025, 3, 8)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 3, 8)),
            preserve_default=False,
        ),
    ]
