# Generated by Django 5.1.5 on 2025-03-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0002_remove_coupon_coupon_type_remove_coupon_expiry_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_active_admin',
            field=models.BooleanField(default=True),
        ),
    ]
