# Generated by Django 5.1.5 on 2025-03-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0003_coupon_is_active_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='summer10', max_length=100),
            preserve_default=False,
        ),
    ]
