# Generated by Django 5.1.5 on 2025-03-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0006_alter_usedcoupon_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField()),
                ('is_active_admin', models.BooleanField(default=True)),
            ],
        ),
    ]
