# Generated by Django 5.1.5 on 2025-02-14 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_side', '0003_remove_products_image_remove_products_variant_unit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_images',
            new_name='ProductImages',
        ),
        migrations.RenameModel(
            old_name='Product_variants',
            new_name='ProductVariants',
        ),
    ]
