# Generated by Django 5.1.5 on 2025-02-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_side', '0005_products_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
