# Generated by Django 5.1.5 on 2025-03-19 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_side', '0006_productvariants_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 19, 5, 30, 12, 652374, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
