# Generated by Django 5.1.5 on 2025-03-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_side', '0007_products_is_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='is_created',
            new_name='created_at',
        ),
    ]
