# Generated by Django 5.1.5 on 2025-04-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_side', '0009_products_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariants',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
