# Generated by Django 5.1.5 on 2025-02-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_customer_is_verified_remove_vendor_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='is_verified_by_admin',
        ),
    ]
