# Generated by Django 5.1.5 on 2025-02-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0003_order_orderitems_payments_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
