# Generated by Django 5.1.5 on 2025-03-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0005_shippingaddress_name_shippingaddress_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='order_item_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='processing', max_length=100),
        ),
    ]
