# Generated by Django 5.1.5 on 2025-03-13 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0006_alter_orderitems_order_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='cart_and_orders.order'),
        ),
    ]
