# Generated by Django 5.1.5 on 2025-03-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0009_orderitems_refund_amount_orderitems_refund_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
