# Generated by Django 5.1.5 on 2025-03-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0010_alter_orderitems_refund_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cancel_time',
        ),
    ]
