# Generated by Django 5.1.5 on 2025-03-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0013_orderitems_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='payment_done_to_vendor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
